### PR TITLE
As a Developer, I want to terminate the complete session of the game by using the key button 'M' so that it closes the game all at once. #71

### PR DESCRIPTION
**Pull request by fayu555**
As a Developer, I want to terminate the complete session of the game by using the key button 'M' so that it closes the game all at once. #71

### CODE REVIEW

**Comment by camberwellbeauty** [comment]
Looks good. This appears to be similar to the quit button I implemented, but I'm guessing your implementation doesn't save the game state. I'd recommend adding information about the M key binding to the README.md file.

**Comment by camberwellbeauty** [comment]
I just confirmed that it doesn't save the game state. I'd include that information in the README.md file if you choose to edit it.

**Comment by fayu555** [comment]
Thank you so much for reviewing it, I have added the information in the README.md file.

**Comment by camberwellbeauty** [comment]
Just found a problem. The terminate button will terminate the game even if the user is typing. Could you please move your termination code to inside this if statement?
"if (!g->typing) {" on line 2350 in main.c

**Comment by austin-wr** [comment]
Seems like a good alternative to Q if the user wants to reset any progress they made during the last session. However, maybe in the future adding a "CONFIRM" of sorts would prevent a player from losing progress when they meant to quit normally.

**Pull request merged**
