### PR TITLE
Issue #35

### PR DESCRIPTION
**Pull request by camberwellbeauty**
#35 
I also altered the README.md file to mention the Q key's purpose.

### CODE REVIEW

**Comment by danielrking4290** [comment]
Looks like you've been very thorough with your work and the documentation thereof. Good job!

**Comment by camberwellbeauty** [comment]
My comments never got merged with the main branch. If there’s a problem, please tell me what needs to be fixed.

**Comment by danielrking4290** [comment]
I don't see a problem. They should get merged with this pull.

**Comment by camberwellbeauty** [comment]
You keep closing this pull request without merging first.

**Comment by danielrking4290** [comment]
My bad. lol

**Pull request merged**
